export default {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  moduleNameMapper: {
    '\\.(gif|ttf|eot|svg|png|jpg)$': '<rootDir>/test/__mocks__/fileMock.tsx',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
  },
  coveragePathIgnorePatterns: [
    '/src/components/Login.tsx',
    '/src/components/Admin/Users/UsersTable.tsx',
    '/src/components/Nav/navBar.tsx',
    '/src/components/productForm/productForm.tsx',
    '/src/components/products/products.tsx',
    '/src/pages/products.tsx',
    '/src/pages/confirmationPage.tsx',
    '/src/redux/action/AccountStatusAction.tsx',
    '/src/redux/action/AddAction.tsx',
    '/src/redux/action/CartAction.tsx',
    '/src/redux/action/ChangeRoleAction.tsx',
    '/src/redux/action/chatAtion.tsx',
    '/src/redux/action/wishlistAction.tsx',
    '/src/redux/reducers/cartViewSlice.tsx',
  ],
  maxWorkers: 2,
};
