export const GET_ITEM_DETAILS_REQUEST = 'GET_ITEM_DETAILS_REQUEST';
export const GET_ITEM_DETAILS_SUCCESS = 'GET_ITEM_DETAILS_SUCCESS';
export const GET_ITEM_DETAILS_FAILURE = 'GET_ITEM_DETAILS_FAILURE';
export const GET_COLLECTION_REQUEST = 'GET_COLLECTION_REQUEST';
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS';
export const GET_COLLECTION_FAILURE = 'GET_COLLECTION_FAILURE';
